server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8177
monitorIp: ${MONITOR_IP}
monitorPort: ${MONITOR_PORT}
influxdbIp: ${INFLUXDB_IP}
influxdbPort: ${INFLUXDB_PORT}
